apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dev-admin
  name: dev-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev-admin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dev-admin
    spec:
      containers:
      - image: registry.gitlab.com/learner.in/neetprepadmin
        imagePullPolicy: Always
        name: neetprepadmin
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "100m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
