apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-admin
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-admin
  targetCPUUtilizationPercentage: 20