branch-defaults:
  master:
    environment: Neepprepadmin-env
global:
  application_name: NeepPrepAdmin
  branch: null
  default_ec2_keyname: learner.pem
  default_platform: Puma with Ruby 2.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
