Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "chapters/section_content"
  get "notes/edit_content/:id", to: "notes#edit_content"
  post "notes/update_content", to: "notes#update_content"
  post "chapters/remove_section_content", to: "chapters#remove_section_content"
  post "chapters/update_and_sort", to: "chapters#update_and_sort"
  get "doubts/pending_stats"
  get "customer_supports/pending_stats"
  get "customer_issues/pending_stats"
  get "doubt_answers/answer"
  get "doubt_answers/connect_user"
  post "doubt_answers/post_answer"
  post "doubt_answers/toggle_good_flag"
  get "user_doubt_counts/stats"
  get "course_details/show"
  get "user_analytics/show"
  get "user_analytics/accuracy"
  post "user_analytics/showAccuracy"
  post "user_analytics/populate_user_activites"
  get "questions/pdf_questions"
  get "questions/easy_questions"
  get "course_invitations/multiple_courses"
  post "course_invitations/createCourseInvitation"
  get "questions/add_explanation/:id", to: "questions#add_explanation"
  post "questions/update_explanation", to: "questions#update_explanation"
  get "questions/test_question_pdf/:id/", to: 'questions#test_question_pdf'
  get "videos/add_chapter_video/:videoId", to: "videos#add_chapter_video"
  post "videos/getSubjectsList"
  post "videos/getChaptersList"
  post "videos/createChapterVideo"
  post "chapters/createChapterVideo"
  post "chapters/remove_chapter_video", to: "chapters#remove_chapter_video"
  post "chapters/update_and_sort_videos", to: "chapters#update_and_sort_videos"
  get "chapters/crud_video/:chapterId", to: "chapters#crud_video"
  get "tests/add_chapter_test/:testId", to: "tests#add_chapter_test"
  get "tests/add_question/:testId", to: "tests#add_question"
  get "tests/crud_question/:testId", to: "tests#crud_question"
  post "tests/remove_test_question", to: "tests#remove_test_question"
  post "tests/update_and_sort", to: "tests#update_and_sort"
  get "tests/add_sequence/:testId", to: "tests#add_sequence"
  get "tests/questions/:id", to: "tests#questions"
  post "tests/getSubjectsList"
  post "/tests/getTestQuestionsList"
  post "tests/getChaptersList"
  post "tests/createTestQuestion"
  post "tests/addTestQuestionSequence"
  post "tests/createChapterTest"
  get "course_details/booster"
  get "test_attempts/aryan_raj_toppers"
  get "payments/generate_url", to: "payments#generate_url"
  get "matviews/forced_update"
  get "google_ads/report"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/admin/answer_count", to: "user_doubt_counts#answer_count"
  post "/admin/get_count", to: "user_doubt_counts#get_count"

  get "/livesession/:id/", to: "group_chats#group"
  get "/teacher/livesession/:id", to: "group_chats#teacher_view"

  get "/sent-notification", to: "notifications#send_notification"

  post "/livesession/create_chat", to: "group_chats#create_chat"
  post "/livesession/block_user", to: "group_chats#block_user"
  post "/livesession/delete_message", to: "group_chats#delete_message"
  post "/livesession/end_chat", to: "group_chats#end_chat"
  post "/livesession/send_question", to: "group_chats#send_question"
  post "/livesession/check_question", to: "group_chats#check_question"
  post "/livesession/show_analytics", to: "group_chats#show_analytics"
end
