Rails.application.routes.draw do
  # Permanently redirect all requests originally to admin1.neetprep.com to newadmin.neetprep.com
  get '/(*path)', to: redirect { |path_params, request|
    "https://newadmin.neetprep.com/#{path_params[:path]}"
  }, status: 301, constraints: { domain: 'admin1.neetprep.com' }

  # ... Remaining application routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "chapters/section_content"
  get "notes/edit_content/:id", to: "notes#edit_content"
  post "notes/update_content", to: "notes#update_content"
  post "notes/duplicate_content", to: "notes#duplicate_content"
  post "chapters/remove_section_content", to: "chapters#remove_section_content"
  post "chapters/update_and_sort", to: "chapters#update_and_sort"
  get "doubts/pending_stats"
  get "customer_supports/pending_stats"
  get "customer_issues/pending_stats"
  get "doubt_answers/answer"
  post "doubt_answers/mark_as_solved"
  get "doubt_answers/connect_user"
  post "doubt_answers/post_answer"
  post "doubt_answers/toggle_good_flag"
  get "user_doubt_counts/stats"
  get "course_details/show"
  get "user_analytics/show"
  get "user_analytics/accuracy"
  post "user_analytics/showAccuracy"
  post "user_analytics/userData"
  get "user_analytics/userData"
  post "user_analytics/populate_user_activites"
  get "questions/pdf_questions"
  get "questions/translation_pdf"
  get "questions/test_translation"
  get "questions/easy_questions"
  get "questions/sub-topic-difficulty", to: "questions#sub_topic_difficutly"
  get "course_invitations/multiple_courses"
  post "course_invitations/createCourseInvitation"
  get "questions/add_explanation/:id", to: "questions#add_explanation"
  post "questions/update_explanation", to: "questions#update_explanation"
  get "questions/add_hint/:id", to: "questions#add_hint"
  post "questions/create_hint_row", to: "questions#create_hint_row"
  post "questions/video_link_hint", to: "questions#video_link_hint"
  post "questions/remove_video_link_hint", to: "questions#remove_video_link_hint"
  get "questions/test_question_pdf/:id/", to: 'questions#test_question_pdf'
  post "questions/sync_course_questions/:id", to: "questions#sync_course_questions"
  post "questions/delete_from_question_banks/:id", to: "questions#delete_from_question_banks"
  post "questions/sync_subject_questions/:id", to: "questions#sync_subject_questions"
  get "videos/add_chapter_video/:videoId", to: "videos#add_chapter_video"
  post "videos/getSubjectsList"
  post "videos/getChaptersList"
  post "videos/createChapterVideo"
  post "chapters/createChapterVideo"
  post "chapters/remove_chapter_video", to: "chapters#remove_chapter_video"
  post "chapters/update_and_sort_videos", to: "chapters#update_and_sort_videos"
  get "chapters/crud_video/:chapterId", to: "chapters#crud_video"
  get "tests/add_chapter_test/:testId", to: "tests#add_chapter_test"
  get "tests/add_question/:testId", to: "tests#add_question"
  get "chapters/add_question/:chapterId", to: "chapters#add_question"
  get "chapters/del_question/:chapterId", to: "chapters#del_question"
  get "chapters/add_note/:chapterId", to: "chapters#add_note"
  get "chapters/del_note/:chapterId", to: "chapters#del_note"
  get "chapters/get_subtopics/:chapterId", to: "chapters#get_subtopics"
  get "chapters/populate_question_chapter_subtopic", to: "chapters#populate_question_chapter_subtopic"
  get "tests/crud_question/:testId", to: "tests#crud_question"
  post "tests/remove_test_question", to: "tests#remove_test_question"
  post "tests/update_and_sort", to: "tests#update_and_sort"
  get "tests/add_sequence/:testId", to: "tests#add_sequence"
  get "tests/questions/:id", to: "tests#questions"
  post "tests/getSubjectsList"
  post "/tests/getTestQuestionsList"
  post "tests/getChaptersList"
  post "tests/createTestQuestion"
  post "chapters/createChapterQuestion"
  post "chapters/deleteChapterQuestion"
  post "chapters/createChapterNote"
  post "chapters/deleteChapterNote"
  post "tests/addTestQuestionSequence"
  post "tests/createChapterTest"
  get "course_details/booster"
  get "test_attempts/aryan_raj_toppers"
  get "payments/generate_url", to: "payments#generate_url"
  get "matviews/forced_update"
  get "google_ads/report"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "generics/flashcardstats", to: "generics#get_flashcard_stats"
  get "generics/create_user_token/:id", to: "generics#create_user_token"
  get "generics/bookmark_during", to: "generics#bookmark_during"

  post "generics/move_flashcard_to_back", to: "generics#set_seq_id_back"
  get "generics/course_access_ar", to: "generics#give_course_access_aryan_raj_view"
  post "generics/course_access_ar", to: "generics#give_course_access_aryan_raj"
  get "generics/bulk_notfiy", to: "generics#bulk_notify"
  post "generics/bulk_notfiy", to: "generics#send_bulk_notification"
  get "generics/get_user_activity", to: "generics#get_user_activity"
  post "generics/user_activity", to: "generics#user_activity"

  get "/admin/answer_count", to: "user_doubt_counts#answer_count"
  post "/admin/get_count", to: "user_doubt_counts#get_count"

  get "/livesession/:id/", to: "group_chats#group"
  get "/teacher/livesession/:id", to: "group_chats#teacher_view"

  get "/sent-notification", to: "notifications#send_notification"

  post "/livesession/create_chat", to: "group_chats#create_chat"
  post "/livesession/block_user", to: "group_chats#block_user"
  post "/livesession/delete_message", to: "group_chats#delete_message"
  post "/livesession/end_chat", to: "group_chats#end_chat"
  post "/livesession/send_question", to: "group_chats#send_question"
  post "/livesession/check_question", to: "group_chats#check_question"
  post "/livesession/show_analytics", to: "group_chats#show_analytics"
  post "/assign_to_me", to: "doubt_answers#assign_to_me"

  get "/coach-dashboard", to: "coaches#show"
  get "/coach-dashboard-summary", to: "coaches#summary"
  #ncert_question_explanation
  get "/ncert-question/:id", to: "admin/questions#show"

  namespace :admin do
    get "/topics/:id/print_flashcards", to: "topics#print_flashcards"
    get "/top_voted_doubt", to: "doubt_chat_doubts#most_voted"

    get "tests/:id/leader_board", to: "tests#leader_board"
    get "tests/:testId/question_selection_test", to: "tests#question_selection"
    get "tests/:chapterId/subtopics_detail", to: "tests#get_subtopics_with_detail"
    post "tests/:testId/add_questions_to_test_with_question_selection", to: "tests#add_questions_to_test_with_question_selection"

    post "/questions/:id/create_translation", to: "questions#create_translation"
    post "/ncert_sentences/find", to: "ncert_sentences#find_by_sentence"
    post "/video_sentences/find", to: "video_sentences#find_by_sentence"
    post "/video_sentences/add_to_question", to: "video_sentences#add_sentence_to_question"
  end
end
