class Doubt < ApplicationRecord
  self.table_name = "Doubt"
  belongs_to :topic, class_name: "Topic", foreign_key: "topicId"
  scope :botany_paid_student_doubts, -> {joins(", \"Topic\", \"SubjectChapter\" WHERE (\"Doubt\".\"teacherReply\" IS  NULL) AND (\"Topic\".\"id\" = \"SubjectChapter\".\"chapterId\" AND (\"SubjectChapter\".\"subjectId\" IN (53) AND (\"SubjectChapter\".\"deleted\" = false)) AND \"Doubt\".\"topicId\" = \"Topic\".\"id\") AND NOT EXISTS (SELECT \"DoubtAnswer\".\"id\" FROM \"DoubtAnswer\" WHERE \"DoubtAnswer\".\"doubtId\" = \"Doubt\".\"id\" ) AND EXISTS (SELECT \"UserCourse\".\"courseId\" FROM \"UserCourse\" WHERE \"UserCourse\".\"userId\" = \"Doubt\".\"userId\" AND \"expiryAt\" >= CURRENT_TIMESTAMP)")}
  scope :chemistry_paid_student_doubts, -> {joins(", \"Topic\", \"SubjectChapter\" WHERE (\"Doubt\".\"teacherReply\" IS  NULL) AND (\"Topic\".\"id\" = \"SubjectChapter\".\"chapterId\" AND (\"SubjectChapter\".\"subjectId\" IN (54) AND (\"SubjectChapter\".\"deleted\" = false)) AND \"Doubt\".\"topicId\" = \"Topic\".\"id\") AND NOT EXISTS (SELECT \"DoubtAnswer\".\"id\" FROM \"DoubtAnswer\" WHERE \"DoubtAnswer\".\"doubtId\" = \"Doubt\".\"id\" ) AND EXISTS (SELECT \"UserCourse\".\"courseId\" FROM \"UserCourse\" WHERE \"UserCourse\".\"userId\" = \"Doubt\".\"userId\" AND \"expiryAt\" >= CURRENT_TIMESTAMP)")}
  scope :physics_paid_student_doubts, -> {joins(", \"Topic\", \"SubjectChapter\" WHERE (\"Doubt\".\"teacherReply\" IS  NULL) AND (\"Topic\".\"id\" = \"SubjectChapter\".\"chapterId\" AND (\"SubjectChapter\".\"subjectId\" IN (55) AND (\"SubjectChapter\".\"deleted\" = false)) AND \"Doubt\".\"topicId\" = \"Topic\".\"id\") AND NOT EXISTS (SELECT \"DoubtAnswer\".\"id\" FROM \"DoubtAnswer\" WHERE \"DoubtAnswer\".\"doubtId\" = \"Doubt\".\"id\" ) AND EXISTS (SELECT \"UserCourse\".\"courseId\" FROM \"UserCourse\" WHERE \"UserCourse\".\"userId\" = \"Doubt\".\"userId\" AND \"expiryAt\" >= CURRENT_TIMESTAMP)")}
  scope :zoology_paid_student_doubts, -> {joins(", \"Topic\", \"SubjectChapter\" WHERE (\"Doubt\".\"teacherReply\" IS  NULL) AND (\"Topic\".\"id\" = \"SubjectChapter\".\"chapterId\" AND (\"SubjectChapter\".\"subjectId\" IN (56) AND (\"SubjectChapter\".\"deleted\" = false)) AND \"Doubt\".\"topicId\" = \"Topic\".\"id\") AND NOT EXISTS (SELECT \"DoubtAnswer\".\"id\" FROM \"DoubtAnswer\" WHERE \"DoubtAnswer\".\"doubtId\" = \"Doubt\".\"id\" ) AND EXISTS (SELECT \"UserCourse\".\"courseId\" FROM \"UserCourse\" WHERE \"UserCourse\".\"userId\" = \"Doubt\".\"userId\" AND \"expiryAt\" >= CURRENT_TIMESTAMP)")}

end
